### ISSUE TITLE
Failure to escape paths in regex patterns causes spurious failures on Windows

### ISSUE THREAD

**Issue by nanis** [kazuho/p5-text-microtemplate#11]
<pre>C:\...\Text-MicroTemplate-0.21> prove -vb t\05-warn.t
t\05-warn.t ..
1..2
ok 1 - output on warn
not ok 2 - warn location

#   Failed test 'warn location'
#   at t\05-warn.t line 27.
#                   'Odd number of elements in hash assignment at line 2 in template passed from t\05-warn.t at line 20.
# ----------------------------------------------------------------------------
#    1: hello
#    2: ? my %h = @_;
#    3: world
# ----------------------------------------------------------------------------
# '
#     doesn't match '(?^: at line 2 .* t\05-warn.t at line \d+)'
# Looks like you failed 1 test of 2.
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/2 subtests</pre>

Solved by escaping the interpolated path in `t\05-warn.t`:

    like $w, qr/ at line 2 .* \Q$0\E at line \d+/, 'warn location';

Same thing in `t\02-render_mt.t`:

<pre>C:\...\Text-MicroTemplate-0.21> prove -vb t\02-render_mt.t
t\02-render_mt.t ..
1..3
ok 1
ok 2 - die on access to nonexistent value
not ok 3

#   Failed test at t\02-render_mt.t line 19.
#                   'Global symbol "$nonexistent" requires explicit package name at line 1 in template passed from t\02-render_mt.t at line 15.
# ----------------------------------------------------------------------------
#    1: hello <?=nonexistent ?>
# ----------------------------------------------------------------------------
# '
#     doesn't match '(?^: at line 1 .*t\02-render_mt.t at line \d+)'
# Looks like you failed 1 test of 3.
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/3 subtests

Test Summary Report
-------------------
t\02-render_mt.t (Wstat: 256 Tests: 3 Failed: 1)
  Failed test:  3
  Non-zero exit status: 1
Files=1, Tests=3,  0 wallclock secs ( 0.08 usr +  0.01 sys =  0.09 CPU)
Result: FAIL</pre>

Fixed by escaping the interpolated path in `t\02-render_mt.t`:

    like $@, qr/ at line 1 .*\Q$0\E at line \d+/;

See also [Sometimes, all it takes is a simple change to make your Perl code run on Windows](http://www.nu42.com/2014/03/sometimes-all-it-takes-is-simple-change.html).

Thanks,

-- Sinan

**Comment by kazuho** [comment]
Thank you for the suggestion.

Would you mind creating a pull request?  I do not have a Windows environment myself and cannot confirm that the fix would work well if I copy-pasted the changes.

**Comment by kazuho** [comment]
fixed in #13.
